#pragma once
#include "extra/OBB2D.hpp"


#include "delegates/CCScrollLayerExtDelegate.hpp"
#include "delegates/ColorSelectDelegate.hpp"
#include "delegates/CustomSFXDelegate.hpp"
#include "delegates/CustomSongDelegate.hpp"
#include "delegates/AnimatedSpriteDelegate.hpp"
#include "delegates/GJDropDownLayerDelegate.hpp"
#include "delegates/GJRotationControlDelegate.hpp"
#include "delegates/GJScaleControlDelegate.hpp"
#include "delegates/GJTransformControlDelegate.hpp"
#include "delegates/GooglePlayDelegate.hpp"
#include "delegates/LevelSettingsDelegate.hpp"
#include "delegates/MusicDownloadDelegate.hpp"
#include "delegates/SetIDPopupDelegate.hpp"
#include "delegates/TextInputDelegate.hpp"
#include "delegates/UploadActionDelegate.hpp"
#include "delegates/UploadPopupDelegate.hpp"
#include "delegates/GJAccountDelegate.hpp"

#include "extra/CCIndexPath.hpp"
#include "extra/TableView.hpp"


#include "cells/TableViewCell.hpp"
#include "cells/LevelCell.hpp"
#include "cells/CommentCell.hpp"

#include "delegates/TableViewDelegate.hpp" 
#include "delegates/TextAreaDelegate.hpp"

#include "extra/BoomListView.hpp" 
#include "extra/CCTextInputNode.hpp"
#include "extra/DialogObject.hpp"
#include "extra/FLAlertProtocol.hpp"
#include "extra/gameToolbox.hpp"
#include "extra/GameObject.hpp"
#include "extra/PlayerObject.hpp"
#include "extra/GJChallengeItem.hpp"
#include "extra/GJSearchObject.hpp" 
#include "extra/GJTransformState.hpp"
#include "extra/levelTools.hpp" 
#include "extra/MultilineBitmapFont.hpp"
#include "extra/textArea.hpp"

#include "FMODAudioEngine/FMODAudioEngine.hpp" 

#include "managers/AchievementManager.hpp"
#include "managers/GJComment.hpp"
#include "managers/GameLevelmanager.hpp"
#include "managers/GManager.hpp" 
#include "managers/GameStatsManager.hpp" 
#include "managers/GJAccountManager.hpp"
#include "managers/GJGameLevel.hpp"
#include "managers/GJLevelList.hpp" 
#include "managers/GJUserScore.hpp"
#include "managers/GameManager.hpp"
#include "managers/SongInfoObject.hpp"
#include "managers/MusicDownloadManager.hpp"

#include "sprites_nodes/achievementBar.hpp" 
#include "sprites_nodes/achievementNotifier.hpp" 
#include "sprites_nodes/buttonSprite.hpp"
#include "sprites_nodes/CCAnimatedSprite.hpp"
#include "sprites_nodes/CCMenuItemSpriteExtra.hpp" 
#include "sprites_nodes/CCMenuItemToggler.hpp" 
#include "sprites_nodes/CCSpritePlus.hpp"
#include "sprites_nodes/CreateMenuItem.hpp"
#include "sprites_nodes/GJDifficultySprite.hpp"
#include "sprites_nodes/GJRobotSprite.hpp" 
#include "sprites_nodes/GJSpiderSprite.hpp"
#include "sprites_nodes/LoadingCircle.hpp"
#include "sprites_nodes/SimplePlayer.hpp"
#include "sprites_nodes/InfoAlertButton.hpp"
#include "sprites_nodes/SliderTouchLogic.hpp"


#include "layers/AccountHelpLayer.hpp"
#include "layers/CCBlockLayer.hpp" 
#include "layers/CCContentLayer.hpp"
#include "layers/CreatorLayer.hpp"
#include "layers/CCScrollLayerExt.hpp"
#include "layers/ChallengesPage.hpp"
#include "layers/CustomSongWidget.hpp"
#include "layers/DialogLayer.hpp"
#include "layers/DrawGridLayer.hpp"
#include "layers/FLALertlayer.hpp" 
#include "layers/EditLevelLayer.hpp"
#include "layers/EditButtonBar.hpp"
#include "layers/EditorPauseLayer.hpp"
#include "layers/EditorUI.hpp"
#include "layers/GJAccountLayer.hpp"
#include "layers/GJBaseGameLayer.hpp"
#include "layers/GJCommentListLayer.hpp" 
#include "layers/GJDropDownLayer.hpp"
#include "layers/GJListLayer.hpp"
#include "layers/MenuGameLayer.hpp"
#include "layers/MenuLayer.hpp" 
#include "layers/MoreSearchLayer.hpp"
#include "layers/MoreOptionsLayer.hpp"
#include "layers/OptionsLayer.hpp"
#include "layers/LeaderboardsLayer.hpp"
#include "layers/LevelBrowserLayer.hpp"
#include "layers/LevelEditorLayer.hpp"
#include "layers/LevelInfoLayer.hpp" 
#include "layers/LevelListLayer.hpp"
#include "layers/LevelPage.hpp"
#include "layers/LoadingLayer.hpp"
#include "layers/PauseLayer.hpp"
#include "layers/PlayLayer.hpp"
#include "layers/ProfilePage.hpp" 
#include "layers/RateStarsLayer.hpp"
#include "layers/SetIDPopup.hpp"
#include "layers/GJSongBrowser.hpp"
#include "layers/SongInfoLayer.hpp"
#include "layers/SupportLayer.hpp"
#include "layers/ScrollingLayer.hpp"
#include "layers/UploadActionPopup.hpp"

#define ccDir cocos2d::CCDirector::sharedDirector()
